### ISSUE TITLE
An error occurs because "Content-Length" does not exist

### ISSUE THREAD

**Issue by madwind76** [vulnersCom/getsploit#4]
My environment is as follows.
Ubuntu : 16.04.3
Python : 2.7.12

```
    ./getsploit.py -u
    Downloading getsploit database archive. Please wait, it may take time. Usually around 5-10 minutes.
    Traceback (most recent call last):
        File "./getsploit.py", line 802, in <module>
            main()
        File "./getsploit.py", line 743, in main
            downloadVulnersGetsploitDB(DBPATH)
        File "./getsploit.py", line 648, in downloadVulnersGetsploitDB
            downloadFile(vulnersURL['updateAPI'], archiveFileName, progress_callback=progress_callback_simple)
        File "./getsploit.py", line 619, in downloadFile
            file_size = int(meta.getheaders("Content-Length")[0])
    IndexError: list index out of range

**Comment by oshall** [comment]
So I really wanted this to work offline since the online version is so useful, thanks team for creating this :-). 

Looks like the headers being returned doesn't include the `Content-Length` header which the script has a dependency on. Since line 619 was failing, doing a `print meta` showed that the field `Content-Length` was not returned:

`
Date: Wed, 10 Jan 2018 22:01:38 GMT
Content-Type: application/x-zip-compressed
Transfer-Encoding: chunked
Connection: close
Content-Disposition: attachment; filename=getsploit.db.zip
X-Vulners-Cache: <NOPE>
X-Vulners-Ratelimit-Reqlimit: 200
X-Vulners-Ratelimit-Burstlimit: 30
X-Vulners-View-Calltime: 118ms
X-Vulners-Calltime: 121ms
X-Vulners-Full-Calltime: 481ms
Set-Cookie: vulnersSession=<NOPE>; Domain=.vulners.com; expires=Wed, 10-Jan-2018 22:01:48 GMT; HttpOnly; Max-Age=10; Path=/; Secure
Server: nginx-wallarm
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
`

**'My' Solution** 
So my blind fix was to hard set an int value at the section that failed, looks like any value will do , but using 1 worked...note, the line number that's failing is dependent upon which python version being used 2>= or <=3:

1. **Option 1 - Change Code**
`#file_size = int(meta.getheaders("Content-Length")[0])`
`file_size = int(1)`

2. **Option 2 - Download and extract**
https://vulners.com/api/v3/archive/getsploit/ , make sure the file is named `getsploit.db` and is in the same directory
**Question:** How often is the archive updated? Because the offline and online results are a bit different.

**Result - Now the local flag works:**
`./getsploit.py --local $search`

**?Suggestion?**
Since the `Content-Length` is not needed as far as my blind personal testing showed, maybe replacing all its uses with what's returned by `Content-Type: application/x-zip-compressed` along with setting a hard value for `file_size=int(1)` since that is what i think is expected by  `_download_helper` for getting a local database.

`if meta.getheaders("Content-Type")[0] == "application/x-zip-compressed":`
`file_size = int(1)`

**Comment by vulnersCom** [comment]
That was a backend problem.
Fixed.
Please, check it out.

**Comment by oshall** [comment]
**Question:** How often is the archive updated? Because the offline and online results are a bit different.

**Confirmed:** Using the unedited script now works without any errors.
**Content-Length: 318167966**

`
curl -I https://vulners.com/api/v3/archive/getsploit/
`
`
HTTP/1.1 200 OK
Date: Fri, 12 Jan 2018 18:57:34 GMT
Content-Type: application/x-zip-compressed
Content-Length: 318167966
Connection: keep-alive
Content-Disposition: attachment; filename=getsploit.db.zip
X-Vulners-Cache: <NOPE>
X-Vulners-Ratelimit-Reqlimit: 200
X-Vulners-Ratelimit-Burstlimit: 30
X-Vulners-View-Calltime: 109ms
X-Vulners-Calltime: 109ms
X-Vulners-Full-Calltime: 116ms
Set-Cookie: vulnersSession=<NOPE>; Domain=.vulners.com; expires=Fri, 12-Jan-2018 18:57:44 GMT; HttpOnly; Max-Age=10; Path=/; Secure
Server: nginx-wallarm
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
`

**Comment by vulnersCom** [comment]
> How often is the archive updated? Because the offline and online results are a bit different.
One time in 4 hours.
But the difference is mainly because in local DB you are using FTS search in sqlite.
And it online search you are using full power of the Vulners Search.
